"use client";

import React, { useState } from "react";
import {
  FileText,
  User,
  Building,
  Calendar,
  DollarSign,
  TrendingDown,
  CheckCircle2,
  Copy,
  ExternalLink,
  ShieldCheck,
  Send,
  Sparkles,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { SAMPLE_BORROWERS } from "@/lib/rasa-dialogue";
import { calculateMortgageComparison } from "@/lib/mortgage-rates";

interface BrokerDocketDrawerProps {
  bookingData?: any;
  onClose?: () => void;
}

export function BrokerDocketDrawer({ bookingData, onClose }: BrokerDocketDrawerProps) {
  const [copied, setCopied] = useState(false);
  const [dispatched, setDispatched] = useState(false);

  // Fallback to sample borrower if no live booking passed
  const sample = SAMPLE_BORROWERS[0];
  const comp = calculateMortgageComparison(sample.currentBalance, sample.currentRatePct);

  const clientName = bookingData?.borrowerName || sample.name;
  const clientPhone = bookingData?.borrowerPhone || sample.phone;
  const clientEmail = bookingData?.borrowerEmail || sample.email;
  const slotTime = bookingData?.slotTime || "Tomorrow 10:00 AM";
  const lender = bookingData?.loanDetails?.currentLender || sample.currentLender;
  const balance = bookingData?.loanDetails?.balance || sample.currentBalance;
  const rate = bookingData?.loanDetails?.currentRate || sample.currentRatePct;

  const crmPayload = {
    event: "broker.annual_review.booked",
    source: "rasa_conversational_engine",
    compliance: "ASIC_RG_273_BID",
    timestamp: new Date().toISOString(),
    client: {
      name: clientName,
      phone: clientPhone,
      email: clientEmail,
      property: sample.propertyAddress,
    },
    loan: {
      currentLender: lender,
      balance: balance,
      ratePct: rate,
      propertyValue: sample.propertyValue,
      lvrPct: Math.round((balance / sample.propertyValue) * 100),
    },
    recommendation: {
      targetLender: comp.recommendedProduct.lender,
      targetRate: comp.recommendedProduct.ratePct,
      monthlySavingsAud: comp.monthlySavings,
      annualSavingsAud: comp.annualSavings,
    },
    appointment: {
      scheduledTime: slotTime,
      type: "Annual Home Loan Review (Video/Phone)",
      durationMinutes: 15,
      brokerCalendarSync: "CalDAV/Google/Outlook_Synced",
    },
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(JSON.stringify(crmPayload, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDispatch = () => {
    setDispatched(true);
    setTimeout(() => setDispatched(false), 3000);
  };

  return (
    <div className="rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] shadow-sm overflow-hidden flex flex-col">
      {/* Header */}
      <div className="p-3.5 sm:p-4 border-b border-[var(--color-border)] bg-[var(--color-surface-subtle)] flex flex-wrap items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <div className="h-8 w-8 rounded-lg bg-emerald-100 dark:bg-emerald-950/60 border border-emerald-200 dark:border-emerald-800 flex items-center justify-center text-emerald-700 dark:text-emerald-300">
            <FileText className="h-4 w-4" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-[var(--color-text-primary)]">
              Broker Fact-Find Handover Docket
            </h3>
            <p className="text-xs text-[var(--color-text-muted)]">
              Pre-qualified CRM packet generated by Rasa dialogue engine upon review confirmation.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Badge variant="outline" className="text-[11px] font-mono border-emerald-300 text-emerald-700 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-950/30 whitespace-nowrap">
            READY FOR BROKERENGINE / SALESTREKKER
          </Badge>
        </div>
      </div>

      <div className="p-4 sm:p-5 space-y-4">
        {/* Top Summary Card */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          <div className="p-3 rounded-lg border border-[var(--color-border)] bg-slate-50 dark:bg-slate-900/60">
            <span className="text-xs font-semibold text-[var(--color-text-muted)] block mb-1">
              Client Identity
            </span>
            <div className="font-bold text-sm text-[var(--color-text-primary)]">{clientName}</div>
            <div className="text-xs text-[var(--color-text-muted)] font-mono">{clientPhone}</div>
            <div className="text-xs text-[var(--color-text-muted)] font-mono">{clientEmail}</div>
          </div>

          <div className="p-3 rounded-lg border border-[var(--color-border)] bg-slate-50 dark:bg-slate-900/60">
            <span className="text-xs font-semibold text-[var(--color-text-muted)] block mb-1">
              Current Mortgage Profile
            </span>
            <div className="font-bold text-sm text-[var(--color-text-primary)]">
              {lender} • A${balance.toLocaleString()}
            </div>
            <div className="text-xs text-rose-600 font-mono font-semibold">
              Current Rate: {rate.toFixed(2)}% p.a.
            </div>
            <div className="text-xs text-[var(--color-text-muted)] font-mono">
              LVR: {Math.round((balance / sample.propertyValue) * 100)}% ({sample.propertyAddress})
            </div>
          </div>

          <div className="p-3 rounded-lg border border-emerald-200 dark:border-emerald-800 bg-emerald-50/50 dark:bg-emerald-950/30">
            <span className="text-xs font-semibold text-emerald-800 dark:text-emerald-300 block mb-1">
              Reserved Review Appointment
            </span>
            <div className="font-bold text-sm text-emerald-700 dark:text-emerald-300 flex items-center gap-1.5">
              <Calendar className="h-3.5 w-3.5 text-emerald-600" />
              <span>{slotTime}</span>
            </div>
            <div className="text-xs text-emerald-600 font-mono font-semibold mt-1">
              Refinance Target: A${comp.annualSavings.toLocaleString()}/yr savings
            </div>
            <div className="text-[11px] text-emerald-800/80 dark:text-emerald-300/80">
              Calendar & SMS Dispatch: Confirmed
            </div>
          </div>
        </div>

        {/* JSON CRM Sync Preview */}
        <div>
          <div className="flex items-center justify-between mb-1.5">
            <span className="text-xs font-semibold uppercase tracking-wider text-[var(--color-text-secondary)]">
              Structured CRM Payload (Webhook Schema)
            </span>
            <div className="flex items-center gap-2">
              <Button
                size="sm"
                variant="outline"
                onClick={handleCopy}
                className="h-7 text-xs font-semibold border-[var(--color-border)] flex items-center gap-1"
              >
                <Copy className="h-3 w-3" />
                <span>{copied ? "Copied JSON" : "Copy Payload"}</span>
              </Button>
              <Button
                size="sm"
                onClick={handleDispatch}
                className="h-7 text-xs font-semibold bg-emerald-600 hover:bg-emerald-700 text-white flex items-center gap-1"
              >
                <Send className="h-3 w-3" />
                <span>{dispatched ? "Webhook Dispatched ✓" : "Simulate CRM Sync"}</span>
              </Button>
            </div>
          </div>

          <pre className="p-3.5 rounded-lg bg-slate-900 text-slate-100 text-xs font-mono overflow-x-auto max-h-56 leading-relaxed border border-slate-800">
            {JSON.stringify(crmPayload, null, 2)}
          </pre>
        </div>
      </div>
    </div>
  );
}
